### ISSUE TITLE
Test and fix any issues with database input safety

### ISSUE THREAD

**Issue by mvbrooks** [techequitycollaborative/tbhi-evidence#31]
ensure that special characters are stripped and the fields are not vulnerable to sql injection

**Comment by iconshocking** [comment]
We should be aware aware that when the dates are read back out from PostgreSQL that they will be converted into local time according to the location of the physical node server. If other services are going to ingest the DB (dashboards, etc.) where dates need to be a consistent entity that doesn't adjust according to where it is viewed, then those services must be sure to handle those dates according to UTC instead of their local time.

**Comment by iconshocking** [comment]
Actually to cut down on the confusion around this, I think the easiest option would be to just export the dates as chars when querying from the DB using `TO_CHAR(expression, format)` since that won't convert them into local time before getting sent over the wire. Then whatever consumer will handle the `YYYY-MM-DD` format in their local time, avoiding the issue.
